// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TagGenerator is an autogenerated mock type for the TagGenerator type
type TagGenerator struct {
	mock.Mock
}

// Random provides a mock function with given fields: chars
func (_m *TagGenerator) Random(chars int) string {
	ret := _m.Called(chars)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(chars)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RandomExcept provides a mock function with given fields: chars, unavailable
func (_m *TagGenerator) RandomExcept(chars int, unavailable []string) (string, error) {
	ret := _m.Called(chars, unavailable)

	var r0 string
	if rf, ok := ret.Get(0).(func(int, []string) string); ok {
		r0 = rf(chars, unavailable)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, []string) error); ok {
		r1 = rf(chars, unavailable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
