// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	scribletop "github.com/scribletop/scribletop-api/modules/scribletop"
	mock "github.com/stretchr/testify/mock"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *UsersService) Create(user scribletop.UserWithPassword) (scribletop.User, error) {
	ret := _m.Called(user)

	var r0 scribletop.User
	if rf, ok := ret.Get(0).(func(scribletop.UserWithPassword) scribletop.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(scribletop.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(scribletop.UserWithPassword) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
