// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mail "github.com/sendgrid/sendgrid-go/helpers/mail"
	mock "github.com/stretchr/testify/mock"

	rest "github.com/sendgrid/rest"
)

// EmailClient is an autogenerated mock type for the EmailClient type
type EmailClient struct {
	mock.Mock
}

// Send provides a mock function with given fields: _a0
func (_m *EmailClient) Send(_a0 *mail.SGMailV3) (*rest.Response, error) {
	ret := _m.Called(_a0)

	var r0 *rest.Response
	if rf, ok := ret.Get(0).(func(*mail.SGMailV3) *rest.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*mail.SGMailV3) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
