// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailSender is an autogenerated mock type for the EmailSender type
type EmailSender struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: dest, subject, filename, bindings
func (_m *EmailSender) SendEmail(dest string, subject string, filename string, bindings interface{}) error {
	ret := _m.Called(dest, subject, filename, bindings)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, interface{}) error); ok {
		r0 = rf(dest, subject, filename, bindings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
