// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	users "github.com/scribletop/scribletop-api/modules/users"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindByEmail provides a mock function with given fields: email
func (_m *Repository) FindByEmail(email string) (*users.UserWithPassword, error) {
	ret := _m.Called(email)

	var r0 *users.UserWithPassword
	if rf, ok := ret.Get(0).(func(string) *users.UserWithPassword); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*users.UserWithPassword)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
