// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	users "github.com/scribletop/scribletop-api/modules/users"
	mock "github.com/stretchr/testify/mock"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *UsersService) Create(user users.UserWithPassword) (users.User, error) {
	ret := _m.Called(user)

	var r0 users.User
	if rf, ok := ret.Get(0).(func(users.UserWithPassword) users.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(users.UserWithPassword) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
