// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// RegisterRoutes provides a mock function with given fields: router
func (_m *Controller) RegisterRoutes(router *gin.RouterGroup) {
	_m.Called(router)
}
